### PR TITLE
Add some icons

### PR DESCRIPTION
**Pull request by luissilva1044894**

### CODE REVIEW

**Comment by israpps** [comment]
Hi!

Could you tell me Wich icons did you add (can't check it now TBH)

**Comment by luissilva1044894** [comment]
- Avatar - Into the Inferno
- Avatar - The Burning Earth
- Batman - Vengeance
- Clock Tower 3
- Blood Will Tell (Dororo)
- Fatal Frame
- Fatal Frame II
- Fatal Frame III
- Guitar Hero Aerosmith
- Guitar Hero - Encore Rocks the 80s
- Gungrave
- Nightshade
- Rayman - Revolution
- Scarface
- Scooby Doo - Mystery Mayhem
- Tarzan Untamed
- Tekken 5
- Yakuza
- Yakuza 2

**Comment by israpps** [comment]
will merge.

But please, in the future, append your new entries to the end of the INI file, the changes you made are distributed in such a way that trying to diff rendered annoying to read diffs.

**Comment by luissilva1044894** [comment]
Needing to double check everytime is worst, ordering it Alphabetically is away better than randomically put the new entries (Nop, older updates weren't on end. I checked both, your and LeonamMiiller changes).

There are more games yet, I'll do a new PR later.

**Comment by israpps** [comment]
Thanks for contributing

**Pull request merged**
