### PR TITLE
Change lang folder from"ko-KR" to "ko"

### PR DESCRIPTION
**Pull request by DDinghoya**

### CODE REVIEW

**Comment by israpps** [comment]
hi!

May I ask what is the purpose of this PR?

**Comment by DDinghoya** [comment]
> hi!
> 
> May I ask what is the purpose of this PR?

In the first folder name "ko-KR", Korean was not output. So, I requested a PR thinking that there would be no problem if I changed the folder name to "ko".

**Comment by israpps** [comment]
sorry for taking so long...

I added the Korean Localization to the program internals...

Just tested and it seems that the program expects the catalog to be located at
```
Lang\ko_KR\HDLBinst.mo
```

**Comment by israpps** [comment]
your issue has been fixed on commit https://github.com/israpps/HDL-Batch-installer/commit/b367cca239f7d1fbf6e930f6703e8352974fcacd

The problem was that the new korean locale was not transferred to the release packages because the ko_KR folder was missing...

Now it should work as i added the wxwidgets Korean locale for standard error messages.
So the folder will always exist from now on

**Comment by DDinghoya** [comment]
> your issue has been fixed on commit [b367cca](https://github.com/israpps/HDL-Batch-installer/commit/b367cca239f7d1fbf6e930f6703e8352974fcacd)
> 
> The problem was that the new korean locale was not transferred to the release packages because the ko_KR folder was missing...
> 
> Now it should work as i added the wxwidgets Korean locale for standard error messages. So the folder will always exist from now on

Thank you for your strong support! :)

It is perfect if only the untranslated square box of the language item is resolved.

HDL-Batch-installer

**Comment by israpps** [comment]
You mean localizing the language names?

**Comment by DDinghoya** [comment]
> You mean localizing the language names?

Yup! There are translated it on po file. However, Not apply them on box

**Pull request closed without merging**
